### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by panicbit** [panicbit/rust-av#10]
- [x] ~~Set up CI #9~~
- [ ] Streamline module structure #7
- [ ] Improve documentation #6
- [ ] Remove the need for raw types in public APIs #4
- [ ] Merge CowPacket/RcPacket/RefPacket into one type #2
- [ ] Improve error handling #3

**Comment by panicbit** [comment]
Closed in favor of milestones
